### ISSUE TITLE
How to hide my cloudant username and password?

### ISSUE THREAD

**Issue by arie741** [arie741/zenblogv2#2] opened 2015-01-21 16:31 UTC
@squest how?

**Comment by squest** [comment] 2015-01-22 09:52
Your problem is not about hiding the username and password. The problem is you are using your global cloudant login (which is the admin for all databases in your account).
So, goto the specific database in your cloudant. And then click permission for that specific database.
Generate API Key (the green button). and you will see a key and password automatically generated.
In the permission menu for that key, set to read and write.
The key is the username and password is the password for that specific database. Now you can change the username/password in your code using this specific database information.

Btw, since this is only for learning, you can keep this clj file on github, next time, you need to set gitignore to ignore this file, you dont want login information on github.

**Comment by squest** [comment] 2015-01-22 10:35
Close this when it's working

**Closed as completed** 2015-01-22 15:40 UTC
